services:
  postgres:
    image: postgres:15-alpine
    container_name: scalable-postgres
    environment:
      POSTGRES_DB: messagedb
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U user -d messagedb"
      interval: "10s"
      timeout: "5s"
      retries: 5

  zookeeper:
    image: zookeeper
    container_name: scalable-zookeeper
    ports:
      - "2181:2181"


  kafka:
    image: confluentinc/cp-kafka
    container_name: scalable-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ${PRIVATE_IP}:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${PRIVATE_IP}.1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
 
  
  redis:
    image: redis
    container_name: scalable-redis
    ports:
      - "6379:6379"


volumes:
  postgres-data:

